version: '3.9'

services:
  server:
    build: .
    ports:
      - '8000:7000'
    depends_on:
      - "db"    
    volumes:
      - ./:/urs/src/app
      - /urs/src/app/node_modules
    environment:
      NODE_ENV: development
      PORT: 7000
      HOST: db
    command: ["npm", "run", "start_app"]  
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'showme007'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: